"""
ProjectWriter: Single source of truth for project outputs.

Mirrors VSCode-style architecture where:
- Python code manages structure and metadata
- Agents provide content but don't create arbitrary files
- All dates come from the system, never the LLM
- Duplicate/redundant files are prevented
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Optional


class ProjectWriter:
    """
    Centralized output management for MiniLab projects.
    
    This class owns the project file structure and ensures:
    - Consistent file organization
    - Correct timestamps (from system, not LLM)
    - No duplicate/redundant files
    - Proper metadata in all documents
    
    Usage:
        writer = ProjectWriter(project_path, project_name)
        
        # Write structured outputs
        writer.write_literature_summary(content)
        writer.write_bibliography(entries)
        writer.write_session_summary(summary)
        
        # Agents should NOT create:
        # - executive_summary.md (use literature_summary.md)
        # - brief_bibliography.md (use references.md)
        # - search_summary.md (goes in transcript)
        # - session_summary.md (orchestrator writes this)
    """
    
    # Canonical project structure
    STRUCTURE = {
        "project_specification.md": "consultation",
        "literature/references.md": "literature_review",
        "literature/literature_summary.md": "literature_review",
        "analysis/": "execute_analysis",
        "figures/": "execute_analysis",
        "outputs/summary_report.md": "writeup_results",
    }
    
    # Files that should NOT be created by agents
    FORBIDDEN_FILES = [
        "executive_summary.md",
        "brief_bibliography.md",
        "search_summary.md", 
        "literature_search_summary.md",
        "session_summary.md",  # Only orchestrator creates this
        "data_manifest.md",    # Only created if data exists
    ]
    
    def __init__(
        self, 
        project_path: Path,
        project_name: str,
        session_date: Optional[datetime] = None
    ):
        """
        Initialize ProjectWriter.
        
        Args:
            project_path: Path to project directory (e.g., Sandbox/my_project)
            project_name: Human-readable project name
            session_date: Session start date (defaults to now)
        """
        self.project_path = Path(project_path)
        self.project_name = project_name
        self.session_date = session_date or datetime.now()
        self._created_files: list[str] = []
        
        # Ensure project directory exists
        self.project_path.mkdir(parents=True, exist_ok=True)
    
    @property
    def date_string(self) -> str:
        """Get formatted date string for documents."""
        return self.session_date.strftime("%B %d, %Y")
    
    @property
    def date_iso(self) -> str:
        """Get ISO formatted date."""
        return self.session_date.strftime("%Y-%m-%d")
    
    @property
    def timestamp(self) -> str:
        """Get current timestamp."""
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def _ensure_dir(self, filepath: Path) -> None:
        """Ensure directory exists for filepath."""
        filepath.parent.mkdir(parents=True, exist_ok=True)
    
    def _add_header(self, title: str, author: str = "MiniLab") -> str:
        """Create standard document header."""
        return f"""# {title}

**Project:** {self.project_name}  
**Date:** {self.date_string}  
**Generated by:** {author}

---

"""
    
    def write_project_specification(self, content: str) -> Path:
        """Write project specification from consultation."""
        filepath = self.project_path / "project_specification.md"
        
        full_content = self._add_header("Project Specification", "MiniLab Agent Bohr")
        full_content += content
        
        filepath.write_text(full_content)
        self._created_files.append(str(filepath))
        return filepath
    
    def write_data_manifest(self, manifest: dict[str, Any]) -> Optional[Path]:
        """
        Write data manifest ONLY if data files exist.
        
        Returns None if no data files found.
        """
        files = manifest.get("files", [])
        if not files:
            return None  # Don't create file if no data
        
        filepath = self.project_path / "data_manifest.md"
        
        content = self._add_header("Data Manifest", "MiniLab")
        content += f"## Summary\n\n"
        content += f"- **Total Files:** {len(files)}\n"
        content += f"- **Total Rows:** {manifest.get('summary', {}).get('total_rows', 0):,}\n\n"
        
        content += "## Files\n\n"
        for f in files:
            content += f"### {f.get('name', 'Unknown')}\n\n"
            content += f"- **Path:** `{f.get('path', 'N/A')}`\n"
            content += f"- **Rows:** {f.get('rows', '?'):,}\n"
            content += f"- **Columns:** {f.get('columns', '?')}\n"
            if f.get("column_names"):
                cols = ", ".join(f["column_names"][:10])
                if len(f["column_names"]) > 10:
                    cols += f" (+{len(f['column_names'])-10} more)"
                content += f"- **Column Names:** {cols}\n"
            content += "\n"
        
        filepath.write_text(content)
        self._created_files.append(str(filepath))
        return filepath
    
    def write_literature_summary(self, content: str) -> Path:
        """Write literature review summary."""
        lit_dir = self.project_path / "literature"
        lit_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = lit_dir / "literature_summary.md"
        
        full_content = self._add_header("Literature Review", "MiniLab Agent Gould")
        full_content += content
        
        filepath.write_text(full_content)
        self._created_files.append(str(filepath))
        return filepath
    
    def write_bibliography(self, content: str) -> Path:
        """Write bibliography/references."""
        lit_dir = self.project_path / "literature"
        lit_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = lit_dir / "references.md"
        
        full_content = self._add_header("Bibliography", "MiniLab Agent Gould")
        full_content += content
        
        filepath.write_text(full_content)
        self._created_files.append(str(filepath))
        return filepath
    
    def write_session_summary(
        self, 
        summary: str,
        session_id: str,
        started_at: str,
        completed_workflows: list[str],
        token_usage: dict[str, Any],
    ) -> Path:
        """
        Write session summary (orchestrator only).
        
        This is the ONLY place session_summary.md should be created.
        """
        filepath = self.project_path / "session_summary.md"
        
        content = self._add_header("Session Summary", "MiniLab Agent Bohr")
        
        # Session metadata
        content += f"**Session ID:** {session_id}  \n"
        content += f"**Started:** {started_at}  \n"
        content += f"**Completed:** {self.timestamp}  \n\n"
        
        # Token usage
        if token_usage:
            content += "## Resource Usage\n\n"
            content += f"- **Tokens Used:** {token_usage.get('total_used', 0):,}\n"
            if token_usage.get('budget'):
                content += f"- **Token Budget:** {token_usage['budget']:,}\n"
                content += f"- **Budget Used:** {token_usage.get('percentage_used', 0):.1f}%\n"
            content += f"- **Estimated Cost:** ${token_usage.get('estimated_cost', 0):.2f}\n\n"
        
        # Completed workflows
        if completed_workflows:
            content += "## Completed Workflows\n\n"
            for wf in completed_workflows:
                content += f"- {wf.replace('_', ' ').title()}\n"
            content += "\n"
        
        # Main summary
        content += "## Summary\n\n"
        content += summary
        
        filepath.write_text(content)
        self._created_files.append(str(filepath))
        return filepath
    
    def write_summary_report(self, content: str) -> Path:
        """Write final summary report."""
        outputs_dir = self.project_path / "outputs"
        outputs_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = outputs_dir / "summary_report.md"
        
        full_content = self._add_header("Summary Report", "MiniLab")
        full_content += content
        
        filepath.write_text(full_content)
        self._created_files.append(str(filepath))
        return filepath
    
    def append_to_file(self, relative_path: str, content: str) -> Path:
        """
        Append content to an existing file.
        
        Use for building up documents incrementally (e.g., references).
        """
        filepath = self.project_path / relative_path
        self._ensure_dir(filepath)
        
        existing = filepath.read_text() if filepath.exists() else ""
        filepath.write_text(existing + content)
        
        return filepath
    
    def get_created_files(self) -> list[str]:
        """Get list of files created by this writer."""
        return self._created_files.copy()
    
    def validate_agent_file(self, filename: str) -> tuple[bool, str]:
        """
        Check if an agent should be allowed to create this file.
        
        Returns (allowed, reason).
        """
        basename = Path(filename).name
        
        for forbidden in self.FORBIDDEN_FILES:
            if forbidden in basename.lower():
                return False, f"File '{basename}' should not be created by agents. Use the canonical structure."
        
        return True, "OK"
    
    def get_canonical_path(self, file_type: str) -> Path:
        """
        Get the canonical path for a type of output.
        
        Args:
            file_type: One of 'bibliography', 'literature_summary', 'project_spec', etc.
        
        Returns:
            Canonical Path for that file type
        """
        mappings = {
            "bibliography": self.project_path / "literature" / "references.md",
            "references": self.project_path / "literature" / "references.md",
            "literature_summary": self.project_path / "literature" / "literature_summary.md",
            "project_spec": self.project_path / "project_specification.md",
            "summary_report": self.project_path / "outputs" / "summary_report.md",
            "session_summary": self.project_path / "session_summary.md",
        }
        
        return mappings.get(file_type, self.project_path / file_type)
